[hooks.lint]
command = "echo 'Linting code'"
description = "Lint code"
modifies_repository = false

[hooks.test]
command = "echo 'Running tests'"
description = "Run tests"
modifies_repository = false

[hooks.format]
command = "echo 'Formatting code'"
description = "Format code"
modifies_repository = true

[groups.pre-commit]
includes = ["lint", "test", "format"]
execution = "parallel"
description = "Pre-commit validation"