# Peter Hook project hooks - using shared Rust quality library
# Imports comprehensive hooks from shared library

imports = ["/Users/jfb/.local/peter-hook/shared.toml"]

# =============================================================================
# PROJECT-SPECIFIC HOOK GROUPS
# =============================================================================

[groups.pre-commit]
includes = ["comprehensive-pre-commit"]
execution = "sequential"
description = "Complete pre-commit quality assurance using shared hooks"

[groups.commit-msg]
includes = ["commit-validation"]
execution = "sequential"
description = "Commit message validation using shared hooks"

[groups.security-focused]
includes = ["security-suite"]
execution = "parallel"
description = "Security checks using shared hooks"

[groups.code-quality]
includes = ["rust-quality"]
execution = "sequential"
description = "Core code quality using shared hooks"

[groups.quick-check]
includes = ["quick-check"]
execution = "sequential"
description = "Fast checks using shared hooks"