# Test advanced features: dependencies, templating, file patterns

[hooks.format]
command = "echo 'Formatting in {HOOK_DIR}'"
description = "Format code with templating"
modifies_repository = true
files = ["**/*.rs"]

[hooks.lint]
command = "echo 'Linting after format'"
description = "Lint code (depends on format)"
modifies_repository = false
files = ["**/*.rs"]
depends_on = ["format"]

[hooks.security]
command = "echo 'Security scan with project {PROJECT_NAME}'"
description = "Security scan (always runs)"
modifies_repository = false
run_always = true

[groups.advanced-test]
includes = ["format", "lint", "security"]
execution = "parallel"
description = "Test dependencies, templating, and file patterns"