name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I also considered...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Hook execution
        - Configuration
        - CLI interface
        - Installation/setup
        - Documentation
        - Performance
        - Other
    validations:
      required: true

  - type: checkboxes
    id: impact
    attributes:
      label: Impact
      description: What would be the impact of this feature?
      options:
        - label: This would improve usability
        - label: This would improve performance
        - label: This would add new functionality
        - label: This would improve reliability
        - label: This would improve documentation

  - type: textarea
    id: examples
    attributes:
      label: Examples or Mock-ups
      description: If applicable, provide examples, mock-ups, or code snippets.
      placeholder: |
        Example configuration:
        ```toml
        [hooks.new-feature]
        option = "value"
        ```

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: Any additional information...