name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # Binary name (matches the name in Cargo.toml)
          bin: peter-hook
          # Target platforms for cross-compilation
          target: x86_64-unknown-linux-gnu,x86_64-apple-darwin,aarch64-apple-darwin,x86_64-pc-windows-msvc,aarch64-unknown-linux-gnu
          # Include additional files in the release archive
          include: LICENSE,README.md,CLAUDE.md,examples
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}